# Makefile for CROBOTS - modern Linux build
#
# Builds the Unix/curses variant of crobots from src/. The historical
# src/makefile.unx is left in place for reference but is not used here;
# it predates bison/flex/pkg-config and no longer builds on this
# toolchain (no `yacc` binary, GCC defaults to a C standard that
# rejects K&R-style declarations).
#
# The DOS backends (src/screend.c, src/screena.c) and their src/makefile.unx
# `dos`/`dosa` targets are untouched and are not built here.

SRC := src

CC      := cc
BISON   := bison
FLEX    := flex
PKGCONF := pkg-config

CURSES_CFLAGS := $(shell $(PKGCONF) --cflags ncurses 2>/dev/null)
CURSES_LIBS   := $(shell $(PKGCONF) --libs ncurses 2>/dev/null || echo -lcurses)

CPPFLAGS := -DUNIX -I$(SRC)
CFLAGS   := -O2 -g -fno-strict-aliasing -Wall -Wextra $(CURSES_CFLAGS)
DEPFLAGS := -MMD -MP
LDLIBS   := -lm $(CURSES_LIBS)

# Generated-parser objects get looser warnings: they're bison/flex output,
# not hand-written code, and warning-clean generated output isn't a goal.
GEN_CFLAGS := -O2 -g -fno-strict-aliasing $(CURSES_CFLAGS)

OBJS := $(addprefix $(SRC)/, \
	main.o grammar.o lexanal.o compiler.o cpu.o intrins.o \
	display.o screen.o motion.o)

GENERATED := $(SRC)/grammar.c $(SRC)/lexanal.c $(SRC)/tokens.h

TARGET := crobots

.PHONY: all clean test

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDLIBS)

# bison produces grammar.c and tokens.h (the -d header) together; a
# grouped target keeps them from being generated by two separate,
# racing recipe invocations under `make -j`.
$(SRC)/grammar.c $(SRC)/tokens.h &: $(SRC)/grammar.y
	$(BISON) -d -o $(SRC)/grammar.c --defines=$(SRC)/tokens.h $<

$(SRC)/lexanal.c: $(SRC)/lexanal.l $(SRC)/tokens.h
	$(FLEX) -o $@ $<

$(SRC)/grammar.o: $(SRC)/grammar.c
	$(CC) $(CPPFLAGS) $(GEN_CFLAGS) -c $< -o $@

$(SRC)/lexanal.o: $(SRC)/lexanal.c
	$(CC) $(CPPFLAGS) $(GEN_CFLAGS) -c $< -o $@

$(SRC)/%.o: $(SRC)/%.c $(SRC)/tokens.h
	$(CC) $(CPPFLAGS) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

-include $(OBJS:.o=.d)

test: $(TARGET)
	@echo "== compile-only =="
	printf '\n\n\n\n' | ./$(TARGET) -c $(SRC)/rabbit.r
	@echo "== headless match (rabbit vs sniper) =="
	printf '\n' | ./$(TARGET) -m5 $(SRC)/rabbit.r $(SRC)/sniper.r
	@echo "== debug trace =="
	printf '\nq\n' | ./$(TARGET) -d $(SRC)/rabbit.r
	@echo "all smoke tests passed"

clean:
	rm -f $(OBJS) $(OBJS:.o=.d) $(GENERATED) $(TARGET)
